# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: set env
      run: |
        echo "##[set-env name=WKDIR;]pwd"
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout doublechaintech/daas-start-kit
      uses: actions/checkout@v2
      with:
        repository: doublechaintech/daas-start-kit
        path: daas-client
    - name: checkout model repo
      uses: actions/checkout@v2
      with:
        path: models
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    # Runs a set of commands using the runners shell
    - name: generate code
      run: |
        $WKDIR/daas-client/gencode.sh $WKDIR/models/model.xml all $WKDIR

    - name: build backend
      run: |
        $WKDIR/bizcore/gradlew -b $WKDIR/bizcore/build.gradle classes
