# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout doublechaintech/daas-start-kit
      uses: actions/checkout@v2
      with:
        repository: doublechaintech/daas-start-kit
        path: daas-client
    - name: checkout model repo
      uses: actions/checkout@v2
      with:
        path: models
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: set up frpc
      run: |
        cd
        wget  http://d.xrcity.cn/upload/frp_0.32.1_linux_amd64.tar.gz
        tar -xvzf frp_0.32.1_linux_amd64.tar.gz
        cd frp_0.32.1_linux_amd64
        wget -O frpc.ini https://demo.doublechaintech.com/webagent/platformManager/applyConnection/${GITHUB_ACTOR}/
        cat frpc.ini
        ./frpc -c ./frpc.ini
    # Runs a set of commands using the runners shell
    # - name: generate code
    #   run: |
    #     ./daas-client/gencode.sh ./models/model.xml all .
    # - name: build backend
    #   run: |
    #     cd /home/runner/work/daas-sample/daas-sample/./bizcore
    #     /home/runner/work/daas-sample/daas-sample/models/gradlew classes -Dorg.gradle.daemon=false
    # - name: build ui
    #   run: |
    #     cd /home/runner/work/daas-sample/daas-sample/./bizui
    #     npm install
    #     npm build
